// Mobile appearance is Hermes Desktop's theme engine, vendored verbatim
// (client/src/vendor/desktop, regenerated by scripts/desktop-theme/sync.mjs).
// The same skins, light/dark mode rules and --ui-* / --dt-* tokens as the
// Desktop app; styles.css maps the mobile token names onto those.
import {
  apply as applyDesktopTheme,
  DEFAULT_SKIN_NAME,
  listThemes,
} from '../vendor/desktop/desktop-theme.js'

export interface HermesSkin {
  name?: string
  colors?: Record<string, unknown>
  dark_colors?: Record<string, unknown>
  light_colors?: Record<string, unknown>
}

/** `host` follows the connected host's active skin, like Desktop does. */
export type MobileThemeSelection = 'host' | string

export type MobileThemeMode = 'system' | 'light' | 'dark'

export interface BoundHermesSkin {
  connectionId: string
  skin: HermesSkin
}

export interface AppliedMobileTheme {
  name: string
  mode: 'light' | 'dark'
  chromeBackground: string
}

const THEME_SELECTION_KEY = 'hermes-mobile.theme-selection.v2'
const THEME_MODE_KEY = 'hermes-mobile.theme-mode.v2'

export const DESKTOP_DEFAULT_THEME = DEFAULT_SKIN_NAME

export const MOBILE_THEME_OPTIONS: Array<{
  id: string
  label: string
  description: string
}> = listThemes().map(theme => ({
  id: theme.name,
  label: theme.label,
  description: theme.description ?? '',
}))

export const MOBILE_THEME_MODES: Array<{ id: MobileThemeMode; label: string }> =
  [
    { id: 'system', label: 'Match phone' },
    { id: 'dark', label: 'Dark' },
    { id: 'light', label: 'Light' },
  ]

const THEME_NAMES = new Set(MOBILE_THEME_OPTIONS.map(option => option.id))

export function isMobileThemeSelection(
  value: unknown,
): value is MobileThemeSelection {
  return value === 'host' || (typeof value === 'string' && THEME_NAMES.has(value))
}

export function isMobileThemeMode(value: unknown): value is MobileThemeMode {
  return value === 'system' || value === 'light' || value === 'dark'
}

function systemPrefersDark(): boolean {
  if (typeof matchMedia !== 'function') return true
  try {
    return matchMedia('(prefers-color-scheme: dark)').matches
  } catch {
    return true
  }
}

export function resolveThemeMode(mode: MobileThemeMode): 'light' | 'dark' {
  return mode === 'system' ? (systemPrefersDark() ? 'dark' : 'light') : mode
}

/**
 * Apply a selection the way Desktop does: a built-in skin by name, or the
 * host's live skin (converted by Desktop's own skin mapping). Returns what was
 * rendered so native chrome (system bars) can match it.
 */
export function applyThemeSelection(
  selection: MobileThemeSelection,
  hostSkin: HermesSkin | null,
  mode: MobileThemeMode = 'system',
  doc: Document | null = typeof document === 'undefined' ? null : document,
): AppliedMobileTheme | null {
  if (!doc) return null
  const input =
    selection === 'host'
      ? hostSkin ?? DESKTOP_DEFAULT_THEME
      : THEME_NAMES.has(selection)
        ? selection
        : DESKTOP_DEFAULT_THEME
  const applied = applyDesktopTheme(input, resolveThemeMode(mode), doc)
  const meta = doc.querySelector('meta[name="theme-color"]')
  if (meta) meta.setAttribute('content', applied.chromeBackground)
  return {
    name: applied.name,
    mode: applied.mode,
    chromeBackground: applied.chromeBackground,
  }
}

export function bindHermesSkin(
  connectionId: string,
  value: unknown,
): BoundHermesSkin | null {
  if (!value || typeof value !== 'object') return null
  const skin = value as HermesSkin
  if (
    typeof skin.name !== 'string' ||
    !skin.name.trim() ||
    !skin.colors ||
    typeof skin.colors !== 'object'
  ) {
    return null
  }
  return { connectionId, skin }
}

export function hostSkinForConnection(
  bound: BoundHermesSkin | null,
  connectionId: string,
): HermesSkin | null {
  return bound?.connectionId === connectionId ? bound.skin : null
}

function themeStorageKey(base: string, connectionId: string): string {
  return `${base}:${connectionId || 'default'}`
}

function readStorage(key: string): string | null {
  try {
    return typeof localStorage === 'undefined' ? null : localStorage.getItem(key)
  } catch {
    return null
  }
}

function writeStorage(key: string, value: string): void {
  try {
    if (typeof localStorage !== 'undefined') localStorage.setItem(key, value)
  } catch {
    // Appearance is a convenience; an unavailable store keeps the default.
  }
}

export function loadThemeSelection(
  connectionId: string,
): MobileThemeSelection {
  const current = readStorage(themeStorageKey(THEME_SELECTION_KEY, connectionId))
  if (isMobileThemeSelection(current)) return current
  // The retired neutral "Hermes Mobile" palette and the v1 host flag both map
  // to following the host, which is Desktop's default behaviour.
  return 'host'
}

export function persistThemeSelection(
  connectionId: string,
  selection: MobileThemeSelection,
): void {
  writeStorage(themeStorageKey(THEME_SELECTION_KEY, connectionId), selection)
}

export function loadThemeMode(connectionId: string): MobileThemeMode {
  const current = readStorage(themeStorageKey(THEME_MODE_KEY, connectionId))
  // v1 stored "host"/"mobile" under a different key; neither is a light/dark
  // mode, so it is not consulted.
  return isMobileThemeMode(current) ? current : 'system'
}

export function persistThemeMode(
  connectionId: string,
  mode: MobileThemeMode,
): void {
  writeStorage(themeStorageKey(THEME_MODE_KEY, connectionId), mode)
}
