#!/usr/bin/env node
/**
 * Regenerate Hermes Mobile's copy of Hermes Desktop's design tokens and theme
 * engine from a Hermes Agent checkout. Run after Desktop's theme changes:
 *
 *   node scripts/desktop-theme/sync.mjs [path-to-hermes-agent]
 *
 * Default checkout: ../hermes-agent next to this project. Uses that checkout's
 * esbuild, else ESBUILD_PATH, else this project's.
 *
 * Writes (all generated, do not hand-edit):
 *   client/src/vendor/desktop/desktop-tokens.css   :root / :root.dark token blocks + @theme vars from styles.css
 *   client/src/vendor/desktop/desktop-theme.js     presets + skin conversion + applyTheme mapping (ESM)
 *   client/src/vendor/desktop/fonts/*.woff2        bundled JetBrains Mono
 *   client/src/vendor/desktop/SOURCE.json          checkout commit + source hashes
 */

import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const pluginRoot = path.resolve(here, '..', '..')
const repo = path.resolve(process.argv[2] || path.join(pluginRoot, '..', 'hermes-agent'))
const desktopSrc = path.join(repo, 'apps', 'desktop', 'src')
const sharedSrc = path.join(repo, 'apps', 'shared', 'src')
const vendor = path.join(pluginRoot, 'client', 'src', 'vendor', 'desktop')

if (!existsSync(path.join(desktopSrc, 'styles.css'))) {
  console.error(`No Hermes Desktop source at ${desktopSrc}. Pass the hermes-agent checkout path.`)
  process.exit(1)
}

mkdirSync(path.join(vendor, 'fonts'), { recursive: true })

// ── Tokens ────────────────────────────────────────────────────────────────
const styles = readFileSync(path.join(desktopSrc, 'styles.css'), 'utf8')

/** Body of the first `{ … }` block whose header matches `header`, searched from `from`. */
function block(source, header, from = 0) {
  const start = source.indexOf(header, from)

  if (start < 0) {
    throw new Error(`styles.css: block "${header}" not found (Desktop layout changed; update this script)`)
  }

  const open = source.indexOf('{', start)
  let depth = 0

  for (let i = open; i < source.length; i++) {
    if (source[i] === '{') depth++
    else if (source[i] === '}' && --depth === 0) return { body: source.slice(open + 1, i), end: i + 1 }
  }

  throw new Error(`styles.css: unbalanced block "${header}"`)
}

const themeInline = block(styles, '@theme inline')
const base = block(styles, '@layer base', themeInline.end)
const rootBlock = block(base.body, ':root {')
const darkBlock = block(base.body, ':root.dark {', rootBlock.end)

const tokens = `/* GENERATED by scripts/desktop-theme/sync.mjs from apps/desktop/src/styles.css. Do not edit. */

@font-face { font-family: 'JetBrains Mono'; font-style: normal; font-weight: 400; font-display: swap; src: url('fonts/JetBrainsMono-Regular.woff2') format('woff2'); }
@font-face { font-family: 'JetBrains Mono'; font-style: normal; font-weight: 700; font-display: swap; src: url('fonts/JetBrainsMono-Bold.woff2') format('woff2'); }
@font-face { font-family: 'JetBrains Mono'; font-style: italic; font-weight: 400; font-display: swap; src: url('fonts/JetBrainsMono-Italic.woff2') format('woff2'); }

/* @theme inline (Tailwind theme variables, emitted as plain custom properties) */
:root {${themeInline.body}}

/* @layer base :root */
:root {${rootBlock.body}}

/* @layer base :root.dark */
:root.dark {${darkBlock.body}}
`

writeFileSync(path.join(vendor, 'desktop-tokens.css'), tokens)

for (const face of ['Regular', 'Bold', 'Italic']) {
  copyFileSync(path.join(desktopSrc, 'fonts', `JetBrainsMono-${face}.woff2`), path.join(vendor, 'fonts', `JetBrainsMono-${face}.woff2`))
}

// Codicons: the icon font Desktop draws every glyph with (CC-BY-4.0).
const codicons = path.join(repo, 'node_modules', '@vscode', 'codicons', 'dist')

if (existsSync(path.join(codicons, 'codicon.css'))) {
  mkdirSync(path.join(vendor, 'codicons'), { recursive: true })
  copyFileSync(path.join(codicons, 'codicon.css'), path.join(vendor, 'codicons', 'codicon.css'))
  copyFileSync(path.join(codicons, 'codicon.ttf'), path.join(vendor, 'codicons', 'codicon.ttf'))
} else {
  console.warn(`Codicons not found at ${codicons}; run npm install in the checkout. Keeping the previous copy.`)
}

// ── Theme engine ──────────────────────────────────────────────────────────
const requireFromRepo = createRequire(path.join(repo, 'package.json'))
let esbuild

try {
  esbuild = requireFromRepo('esbuild')
} catch {
  esbuild = process.env.ESBUILD_PATH
    ? createRequire(import.meta.url)(process.env.ESBUILD_PATH)
    : createRequire(import.meta.url)('esbuild')
}

await esbuild.build({
  entryPoints: [path.join(here, 'entry.ts')],
  outfile: path.join(vendor, 'desktop-theme.js'),
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'chrome120',
  legalComments: 'none',
  banner: { js: '/* GENERATED by scripts/desktop-theme/sync.mjs from Hermes Desktop themes. Do not edit. */' },
  plugins: [
    {
      name: 'desktop-paths',
      setup(build) {
        // presets.ts imports THEME_PRESET_PALETTES from the shared barrel; point it
        // at the one module it needs so the bundle stays small.
        const exact = {
          '@hermes/shared': path.join(sharedSrc, 'theme-presets.ts'),
          '@hermes/shared/color': path.join(sharedSrc, 'color.ts'),
          '@hermes/shared/skin': path.join(sharedSrc, 'skin.ts')
        }

        build.onResolve({ filter: /^@hermes\/shared(\/.*)?$/ }, args => {
          const target = exact[args.path]

          if (!target) {
            return { errors: [{ text: `Unmapped Desktop import ${args.path}; add it to sync-desktop-theme.mjs` }] }
          }

          return { path: target }
        })
        build.onResolve({ filter: /^@desktop\// }, args => ({
          path: path.join(desktopSrc, `${args.path.slice('@desktop/'.length)}.ts`)
        }))
      }
    }
  ]
})

// ── Provenance ────────────────────────────────────────────────────────────
const hash = file => createHash('sha256').update(readFileSync(file)).digest('hex').slice(0, 12)
let commit = 'unknown'

try {
  commit = execFileSync('git', ['-C', repo, 'rev-parse', '--short=11', 'HEAD'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim()
} catch {
  // Not a git checkout; hashes still identify the sources.
}

const sources = ['styles.css', 'themes/presets.ts', 'themes/skin.ts', 'themes/color.ts', 'themes/context.tsx']
writeFileSync(
  path.join(vendor, 'SOURCE.json'),
  JSON.stringify(
    { commit, generated: new Date().toISOString(), sources: Object.fromEntries(sources.map(s => [s, hash(path.join(desktopSrc, s))])) },
    null,
    2
  ) + '\n'
)

console.log(`Synced Desktop theme from ${repo} (${commit}) into ${vendor}`)
